### ISSUE TITLE
Status frame initial width incorrect with tekticles

### ISSUE THREAD

**Issue by Phanx** [TekNoLogic/TourGuide#1]
When using an addon to change the font (such as tekticles), the status frame is initially the wrong width. It's usually too short, resulting in the text being truncated. It's correctly sized if I click past the current objective, but it's annoying to have to open the objectives lise and un-check the thing I just checked to get it back. This has occured with all versions I've ever used... I've just been lazy and forgotten to report it. There's probably a more elegant solution than updating the status frame on every ADDON_LOADED event, but I'd even settle for some way of forcing an update from an external addon. :P

**Comment by tekkub** [comment]
There's no way to detect when a font is changed short of hooking <code>SetFont</code> on every font object, watching ADDON_LOADED for all the font-changing addons out there, or optdepping them in the TOC.  None of which seem to be an elegant way to solve an issue that goes away after you complete the first objective.

If you've got a nice simple clean solution, I'm listening.

**Comment by tekkub** [comment]
Actually, screw it, I'll just resize on every ADDON_LOADED

**Comment by tekkub** [comment]
Force status frame resize on ADDON_LOADED in case of font changes

Closed by d515f0702fbbfcf4c915c64e505bcf6148435cbd
