### ISSUE TITLE
Not detecting my quest acceptances

### ISSUE THREAD

**Issue by levin-zz** [TekNoLogic/TourGuide#11]
When I accept a quest, Tour Guide no longer detects that I did so - also, when I try to manually mark that I've accepted, it automatically marks that I completed and turned in the quest.   This began after a computer crash that also reset my progress by a few steps.

**Comment by tekkub** [comment]
Make sure you're not using an addon that modifies things in the API (quest level addons love to do this).  Also make sure you're not minimizing groups in the quest log.
