### ISSUE TITLE
Feature Request: Waypoint Override

### ISSUE THREAD

**Issue by Korrasera** [TekNoLogic/TourGuide#12]
Sometimes LightHeaded throws up incorrect coords.  When I specify my own, both coordinates get thrown up, but the LightHeaded ones seem to take priority.  Could you add something to the guide structure so that if I put it in, TourGuide ignores LightHeaded and only throws up the coordinate information I gave it?  Like |WO|This Coordinate Here (0.0, 0.0)| or something like that?

**Comment by tekkub** [comment]
It would be better if you simply report the NPC that has bad data to clad so he can account for it in LH.  I believe he already has a few that are flagged as bad.

**Comment by Korrasera** [comment]
Oh, huh, I wasn't aware you could do that.  Thanks for that!
