### ISSUE TITLE
Quest Never Accepted - Barrens (12-20)

### ISSUE THREAD

**Issue by Dyonovan** [TekNoLogic/TourGuide#14]
In the guide, the quest 'Tribes at War' (Camp Taurajo) is never accepted yet it asks to be completed and handed in.

Recommend picking it up after 'Lost in Battle' is completed and before 'Consumed by Hatred' is started.

**Comment by tekkub** [comment]
Missed a quest accept.

Closed by 467a56078441388a640817193df334e590e554d6
