### ISSUE TITLE
Guide: Feralas (45-46) - missing step

### ISSUE THREAD

**Issue by MrRik** [TekNoLogic/TourGuide#16]
(This guide doesn't have a creator's name attached, so I assume it's one of the "default" guides.)

Early on in the guide you pick up the quest "A Strange Request", which tells you to take a shrunken head to Xerash Fireblade at the Lariss Pavilion. It's listed in the guide as "! A Strange Request" (with the exclamation point, indicating I should accept the quest).

There is no step instructing you to actually turn in the quest to Xerash. Since I try to follow the guide step-by-step, in order, I never did take the head to Xerash.

Then, very late in the guide, after it has sent me to Orgrimmar to turn in a number of quests, I see "? A Strange Request", and the guide points me to somebody in the Cleft of Shadow in Org. There's nobody there with a "?" over their head.

So I flew all the way back to Feralas (having already set my hearth to Org) and talked to Xerash, who then sent me back to talk to Witch Doctor Uzer'i. (Quest: Return to Witch Doctor Uzer'i - this quest is left out of the guide.) **At this point, the quest "A Strange Request" showed as completed at the step in Orgrimmar**.

After talking to Uzer'i to complete "Return to Witch Doctor Uzer'i", he had two new quests to offer, neither of which involved talking to anybody in the Cleft of Shadow in Org.

**Comment by tekkub** [comment]
Fix up horde Feralas guide, seems some quests were tweaked in 3.2

Closed by df0498e52611ba92e537314cec6198b217958760
