### ISSUE TITLE
Auto complete 

### ISSUE THREAD

**Issue by SWAT3050** [TekNoLogic/TourGuide#17]
When i accept a quest it dosent go to the next step, also when i try to click the check box it auto checks all of the boxes for that quest so i cant follow it. Please help me fix it i just hit 79 and i want 80!

**Comment by tekkub** [comment]
You have another addon interfering with TG's ability to read the quest log.

**Comment by SWAT3050** [comment]
I fixed it. I just updated all of my addons and now it wirks great again thx.
