### ISSUE TITLE
Quests in Azuremyst/Bloodmyst that are Draenei only. And other alliance starting zones for other races

### ISSUE THREAD

**Issue by Smj-zz** [TekNoLogic/TourGuide#18]
Alliance Azuremyst Isle(1-12) Draenei only.

Medicinal Porpose qid: 9463
An Alternative Alternative qid: 9473
Warn Your People qid: 9622
You Survived! qid: 9279
Rescue the Survivors! qid: 9283

Alliance Bloodmyst Isle(12-20) Draenei only.

Beds, Bandages, and Beyond qid: 9603
On the Wings of a Hippogryph qid: 9604
Hippogryph Master Stephanos qid: 9605
Return to Topher Loaal qid: 9606

Alliance Elwynn Forest(1-12) Human only.

Consecrated Letter qid: 3101
Glyphic Letter qid: 3104
Encrypted Letter qid: 3102
Simple Letter qid: 3100
Hallowed Letter qid: 3103
Tainted Letter qid: 3105

Alliance Teldrassil(1-12) Night Elf only.

Encrypted Sigil qid: 3118
Etched Sigil qid: 3117
Hallowed Sigil qid: 3119
Simple Sigil qid: 3116
Verdant Sigil qid: 3120

**Comment by tekkub** [comment]
Some race-specific starter zone quests

Closed by 9eea90e5227bfe2207248e4aaff41c54a66ee571
