### ISSUE TITLE
Quests with the wrong QID's in guides.

### ISSUE THREAD

**Issue by Smj-zz** [TekNoLogic/TourGuide#19]
Alliance Tanaris (47-48)

Rise of the Silithid  real qid: 162             (old qid: 4267 mixed up with the quest with the same name from a feralas questline)

Alliance Tanaris (43)

Water Pouch Bounty real qid: 1707   (old qid: 1878 mixed up with the repeatable quest with same name that is available after you finish the first one)

**Comment by tekkub** [comment]
Bad QIDs

Closed by 3d66d2d0106858e02d70a5585c3cbedd22349999
