### ISSUE TITLE
Alliance/Draenei Issue

### ISSUE THREAD

**Issue by Pathologick** [TekNoLogic/TourGuide#24]
Whenever I try to level up a draenei warrior of mine, the following error appears upon login (even with all addons but TourGuide, TomTom, Lightheaded, and guides from WoW-Pro disabled):

Date: 2009-10-29 00:57:54
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\TomTomFu2\locale\locale-enUS.lua line 1:
   Cannot find a library instance of "AceLocale-3.0".
Debug:

   !Swatter\Support\LibRevision.lua:47: LibStub()
   TomTomFu2\locale\locale-enUS.lua:1: in main chunk
AddOns:
  Swatter, v5.6.4424 (KangaII)
  LightHeaded, v298
  TomTom, vwowi:revision
  TomTomFu2, v1
  BlizRuntimeLib_enUS v3.2.2.30200 <us>
  (ck=84)

This was done with only one extra addon enabled, Swatter, so that the bug report wouldn't be so cluttered. 

It may be noteworthy that when using my normal set of addons on the same Draenei, none of them function after this error.

Thanks for your time.

**Comment by tekkub** [comment]
What does that have to do with TourGuide?  The error was thrown from TomTomFu2...

**Comment by Pathologick** [comment]
My apologies then, I don't claim to know much about addons and all that. Thank you, and keep up the good work!
