### ISSUE TITLE
Request: Auto complete and key binding

### ISSUE THREAD

**Issue by ImmortalDragon** [TekNoLogic/TourGuide#26]
First request is auto complete for quest turn ins. Would make leveling so much nicer for us who've already read the quests. But I could understand if this is something you don't want to add.

Second is a key binding for the Quest Item button. So instead of having to click the icon, I could just press a key on my keyboard and move on.

**Comment by millhench** [comment]
If you wish to use the "use item" frame from a keybind or your actionbar, make a macro: "/click TourGuideItemFrame"

**Comment by tekkub** [comment]
What he said.  Autocomplete will never be part of TG, use an addon specifically for that if you want it.
