### ISSUE TITLE
Latest Beta doesn't work with Tomtom anymore.

### ISSUE THREAD

**Issue by Andf** [TekNoLogic/TourGuide#29]
Good Evening,
I downloaed latest version (3.3.0.56-Beta) but it has a pretty annoying problem. It doesn't work with Tomtom, no waypoints are set. I get the following error:

[2010/05/02 18:53:56-1625-x8]: tomQuest2-3.3.3 release 4\tomQuest2.lua:3255: Usage: GetQuestLogTitle(index)
tomQuest2-3.3.3 release 4\tomQuest2.lua:3255: in function <Interface\AddOns\tomQuest2\tomQuest2.lua:3253>
(tail call): ?:
<in C code>: in function `RemoveQuestWatch'
TourGuide-3.3.0.56\Broker.lua:61: in function`UpdateStatusFrame'
TourGuide-3.3.0.56\QuestTracking.lua:50: in function <Interface\AddOns\TourGuide\QuestTracking.lua:44>
<in C code>: in function `pcall'
TourGuide-3.3.0.56\Dongle.lua:247: in function <Interface\AddOns\TourGuide\Dongle.lua:246>
TourGuide-3.3.0.56\Dongle.lua:334: in function <Interface\AddOns\TourGuide\Dongle.lua:328>

Reverting to previous TourGuide version solve my problems.
Would you like to help, please? Thanks!

**Comment by Ravendwyr** [comment]
Update or remove tomQuest. TourGuide works fine for me.

**Comment by Andf** [comment]
Not that great hint... TomQuest is up to date and I'd prefer to do not remove it of course. Thanks anyway.Most probably you mean to ask the developer to check TomQuest.
