### ISSUE TITLE
TG & TQ2

### ISSUE THREAD

**Issue by Andf** [TekNoLogic/TourGuide#33]
Good Evening,
I downloaed latest version (3.3.0.56-Beta) but it has a pretty annoying problem. It doesn't work with Tomtom, no waypoints are set. I get the following error:

tomQuest2-3.3.3 release 4\tomQuest2.lua:3255: in function <Interface\AddOns\tomQuest2\tomQuest2.lua:3253>
(tail call): ?: : in function RemoveQuestWatch' TourGuide-3.3.0.56\Broker.lua:61: in functionUpdateStatusFrame'
TourGuide-3.3.0.56\QuestTracking.lua:50: in function <Interface\AddOns\TourGuide\QuestTracking.lua:44>
: in function `pcall'
TourGuide-3.3.0.56\Dongle.lua:247: in function <Interface\AddOns\TourGuide\Dongle.lua:246>
TourGuide-3.3.0.56\Dongle.lua:334: in function <Interface\AddOns\TourGuide\Dongle.lua:328>

Reverting to previous TourGuide version solve my problems.
Would you like to help, please? Thanks!

P.S.

I unintentionally closed my previous ticket, so I had to re-open it, I apologize.

**Comment by tekkub** [comment]
I can't fix bugs in other addons.

**Comment by Andf** [comment]
Thank you, I already asked for TQ2's author help.
