### ISSUE TITLE
Feature Request: SendAddonMessage

### ISSUE THREAD

**Issue by Satissis** [TekNoLogic/TourGuide#34]
Hi Tekkub.
Love this addon.

I'm currently working on a fishing guide using Tour Guide as it's core system.
Now since Tour Guide is build fore leveling guides and not fishing leveling guides, I have to add some new auto complete functions witch is working fine so far.
Just a note: I have not changed your code at all since it can be done outside Tour Giude

I don't know if  there is a event fired already from Tour Guide like the one I'm looking fore but I need to ask since I can't find anything about it so far.

What I would like to request is that you make a SendAddonMessage on guide selection and guide change.

That will make me able to make some checks and auto complete before the guide is shown in Tour Guide interface.
With that I will be able to complete objectives before the user need to do it manually

Kind regards
Satissis

**Comment by tekkub** [comment]
Sorry, TG is not designed for tradeskill leveling.  You should make your own standalone addon for that.

**Comment by Satissis** [comment]
Not that I want to argue with you or anything but it's already a standalone addon. I have none of TG code in it.
TG is just like the handler for a guide that have been released to TG nothing more :)

But what the hell :) Then I'll have to find another way or drop that  function I was planing. It's my first mod that I'm doing so I have allot to learn yet :)

Kind regards
Satissis
