### ISSUE TITLE
Locating quests / Not in guide

### ISSUE THREAD

**Issue by aprilfool79** [TekNoLogic/TourGuide#46]
Just downloaded and installed.  Loads fine, but the quests that it says I need to get, I can't find, and the only ones I _DO_ find, it says aren't in the guide.  I'm lvl 54 right now, in Felwood.  "Forces of Jaednar", "Verifying the Corruption", "Timbermaw Ally", and "Cleansing Felwood" are the ones it says I should accept, but the only ones available are "A Talking Totem" and "Corruption of the Jadefire".

I'm using version  4.0.0.57 of TourGuide, with the stock guides (Felwood, LVL 54)

**Comment by tekkub** [comment]
Most of the 1-60 guides haven't been updated for cat yet.

**Comment by aprilfool79** [comment]
## I don't have Cat, just BC. I just started playing a few weeks ago, can't afford any of the expansions yet. Would this make a difference?

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

tekkub reply@reply.github.com wrote:

Most of the 1-60 guides haven't been updated for cat yet.

##

**Comment by tekkub** [comment]
If you just started playing you should not be using TG.  TG is intended for people leveling their second or third toon.
