### ISSUE TITLE
Show multiple objectives

### ISSUE THREAD

**Issue by ghost** [TekNoLogic/TourGuide#6]
Love the addon. Makes leveling so much easier. Whenever I'm using it though, I'm wondering what's coming up next. And sometimes I need a reminder of what I just did.

Probably not the easiest change to make, but I'd love if I could specify two things:
- Total number of objectives to show
- Number of previous objectives to show.

So if I say 5 total and 2 previous, my current objective will be on the third line with the previous two above it (checked off) and the next two below it.

Especially handy in those instances where, say, there's a named mob to kill.. and the next objective is to kill a bunch of mobs in the same area as him. Since I can't see that objective, I tend to try to sneak around them and just get the kill I need.

**Comment by tekkub** [comment]
Will not implement.  Automatic tracking and the full objective list cover 90% of this, good guide design covers the rest.  If the guide is well designed, you shouldn't need to think ahead and plan which objective to finish first, just complete the one that's shown.

**Comment by ghost** [comment]
Well I'm using the guides that come with it! You're right though that the full objective list basically covers it... if I could configure that list to scale it down, show fewer line items, and hide the objective notes then I could keep it on the screen full time and have exactly what I want.  Is that doable? :)
