### ISSUE TITLE
Show a note identifier

### ISSUE THREAD

**Issue by ghost** [TekNoLogic/TourGuide#7]
Another handy idea would be to have a little icon or even just an asterisk to signify when there's a note associated with the current objective so I know to hover my mouse over it and see what the note is. :-)

**Comment by tekkub** [comment]
"[?]"

**Comment by ghost** [comment]
That'd work :-D

**Comment by ghost** [comment]
Heh.. umm.. this feature is already in TourGuide, huh?  You'd think I'd notice it after having spent months using it. _wipes the egg off his face_
